stages:
- name: Test Client
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile.dev
      buildContext: ./client
      tag: react-test:${CICD_EXECUTION_SEQUENCE}
  - runScriptConfig:
      image: mschregardus/react-test
      shellScript: |-
        docker run react-test:${CICD_EXECUTION_SEQUENCE} npm run test -- --coverage
timeout: 60
notification: {}
